Repository entando-k8s/entando-k8s-app-controller, pull requests merged in 2020-10, with the labels that each got.

#17 ENG-1266 implemented support for GIT over SSH
  jenkins-x.yml
  pom.xml
  src/main/java/org/entando/kubernetes/controller/app/ComponentManagerDeployableContainer.java
  src/test/java/org/entando/kubernetes/controller/app/inprocesstests/DeployEntandoServiceTest.java
  src/test/java/org/entando/kubernetes/controller/app/interprocesstests/AddEntandoAppBaseIT.java
Labels: approved, size/M

#18 Eng 872 bumped to latest
  charts/preview/templates/operator-role.yaml
  pom.xml
  src/main/java/org/entando/kubernetes/controller/app/EntandoAppController.java
  src/main/java/org/entando/kubernetes/controller/app/EntandoAppDeploymentResult.java
  src/main/java/org/entando/kubernetes/controller/app/EntandoAppServerDeployable.java
  src/main/java/org/entando/kubernetes/controller/app/EntandoDatabaseConsumingContainer.java
  src/test/java/org/entando/kubernetes/controller/app/EntandoAppDeployableContainerTest.java
  src/test/java/org/entando/kubernetes/controller/app/inprocesstests/DeployEntandoDbConsumerTest.java
  src/test/java/org/entando/kubernetes/controller/app/inprocesstests/DeployEntandoDbTest.java
  src/test/java/org/entando/kubernetes/controller/app/inprocesstests/DeployEntandoOnExternalDbTest.java
  src/test/java/org/entando/kubernetes/controller/app/inprocesstests/DeployEntandoServiceTest.java
  src/test/java/org/entando/kubernetes/controller/app/inprocesstests/DeployEntandoWithEmbeddedDbTest.java
  src/test/java/org/entando/kubernetes/controller/app/inprocesstests/EntandoDbConsumingDeployable.java
  src/test/java/org/entando/kubernetes/controller/app/interprocesstests/AddEntandoAppBaseIT.java
  src/test/java/org/entando/kubernetes/controller/app/interprocesstests/AddEntandoAppWithContainerizedDatabaseIT.java
  src/test/java/org/entando/kubernetes/controller/app/interprocesstests/AddEntandoAppWithExternalOracleDatabaseIT.java
  src/test/java/org/entando/kubernetes/controller/app/interprocesstests/AddEntandoAppWithExternalPostgresqlDatabaseIT.java
Labels: approved, size/L

#19 ENG-1329 implemented clustered cache support
  pom.xml
  src/main/java/org/entando/kubernetes/controller/app/AppBuilderDeployableContainer.java
  src/main/java/org/entando/kubernetes/controller/app/ComponentManagerDeployableContainer.java
  src/main/java/org/entando/kubernetes/controller/app/EntandoAppDeployableContainer.java
  src/test/java/org/entando/kubernetes/controller/app/inprocesstests/DeployEntandoDbConsumerTest.java
  src/test/java/org/entando/kubernetes/controller/app/inprocesstests/DeployEntandoOnExternalDbTest.java
  src/test/java/org/entando/kubernetes/controller/app/inprocesstests/DeployEntandoServiceTest.java
  src/test/java/org/entando/kubernetes/controller/app/inprocesstests/EntandoDbConsumingDeployable.java
Labels: approved, size/M

#20 FIregloves into owners
  OWNERS
Labels: size/XS

#21 ENG-1329 cluster support
  src/main/java/org/entando/kubernetes/controller/app/EntandoAppDeployableContainer.java
  src/main/java/org/entando/kubernetes/controller/app/EntandoAppServerDeployable.java
  src/test/java/org/entando/kubernetes/controller/app/inprocesstests/DeployEntandoWithEmbeddedDbTest.java
Labels: approved, size/M

#22 ENG-1329 bumped to latest operator-common for cosmetic change
  pom.xml
Labels: size/XS
