Repository entando-k8s/entando-k8s-app-controller, pull requests merged in 2020-07, with the labels that each got.

#7 Eng 698 readiness probe endpoint
  src/main/java/org/entando/kubernetes/controller/app/EntandoAppDeployableContainer.java
  src/test/java/org/entando/kubernetes/controller/app/EntandoAppDeployableContainerTest.java
  src/test/java/org/entando/kubernetes/controller/app/inprocesstests/DeployEntandoServiceTest.java
  src/test/java/org/entando/kubernetes/controller/app/interprocesstests/AddEntandoAppBaseIT.java
Labels: approved, size/M

#8 Eng 529 db connection restore
  src/main/java/org/entando/kubernetes/controller/app/EntandoAppDeployableContainer.java
  src/main/java/org/entando/kubernetes/controller/app/EntandoDatabaseConsumingContainer.java
  src/main/java/org/entando/kubernetes/controller/app/JbossDatasourceValidation.java
  src/test/java/org/entando/kubernetes/controller/app/inprocesstests/DeployEntandoDbConsumerTest.java
  src/test/java/org/entando/kubernetes/controller/app/inprocesstests/DeployEntandoServiceTest.java
  src/test/java/org/entando/kubernetes/controller/app/inprocesstests/EntandoDbConsumingDeployable.java
  src/test/java/org/entando/kubernetes/controller/app/testutils/EnvVarAssertionHelper.java
Labels: approved, size/L

#9 ENG-787 modified the deployable containers to take spec.parameters
  pom.xml
  src/main/java/org/entando/kubernetes/controller/app/AppBuilderDeployableContainer.java
  src/main/java/org/entando/kubernetes/controller/app/ComponentManagerDeployableContainer.java
  src/test/java/org/entando/kubernetes/controller/app/inprocesstests/DeployEntandoServiceTest.java
Labels: approved, size/S

#10 ENG-787 change REACT_APP_DOMAIN back to DOMAIN
  src/main/java/org/entando/kubernetes/controller/app/AppBuilderDeployableContainer.java
  src/test/java/org/entando/kubernetes/controller/app/inprocesstests/DeployEntandoServiceTest.java
Labels: approved, size/XS

#11 ENG-932 supporting db password reset
  pom.xml
  src/test/java/org/entando/kubernetes/controller/app/interprocesstests/AddEntandoAppWithExternalPostgresqlDatabaseIT.java
Labels: approved, size/S
